name: KeyMirror
on: [push]
jobs:
  test-keymirror:
    name: test-keymirror
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3       

      - uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.18.0-rc1'
      
      - name: execute tests
        run: make test
      
